SELECT 
   team_number,
  count(auto_goalie) AS 'matches_played',
  count(auto_goalie) - sum(auto_goalie) as 'auto_normal',
  avg(auto_goalie) AS 'auto_goalie',
  avg(auto_high_hot) AS 'auto_high_hot',
  avg(auto_high_cold) AS 'auto_high_cold',
  avg(auto_high_miss) AS 'auto_high_miss',
  avg(auto_low_hot) AS 'auto_low_hot',
  avg(auto_low_cold) AS 'auto_low_cold',
  avg(auto_low_miss) AS 'auto_low_miss',
  avg(auto_mobility) AS 'auto_mobility',
  avg(auto_block) AS 'auto_block',
  avg(auto_block_miss) AS 'auto_block_miss',
  avg(auto_block+auto_block_miss) AS 'auto_block_total',
  avg(tele_defense_time) AS 'tele_defense_time',
  avg(tele_block) AS 'tele_block',
  avg(no_show) AS 'no_show',
  avg(tipped) AS 'tipped',
  avg(lost_comms) AS 'lost_comms',
  avg(broke_down) AS 'broke_down',
  avg(fouls) as 'fouls',
  avg(tech_fouls) as 'tech_fouls',
  avg(fouls*20 + tech_fouls*50) as 'foul_points',
  ROUND(avg(case when driving_rating = 0 then null else driving_rating end), 1) as 'driving_rating', -- don't count zeros into these, they mean N/A
  ROUND(avg(case when pushing_rating = 0 then null else pushing_rating end), 1) as 'pushing_rating',
  ROUND(avg(case when defense_rating = 0 then null else defense_rating end), 1) as 'defense_rating',
  avg(catch+human_load+floor_load+other_possess) as 'possessions',
  avg(tele_high_score) as 'tele_high_score',
  avg(tele_high_miss) as 'tele_high_miss',
  avg(tele_low_score) as 'tele_low_score',
  avg(tele_low_miss) as 'tele_low_miss',
  avg(truss) as 'truss',
  avg(truss_miss) as 'truss_miss',
  avg(catch) as 'catch',
  avg(catch_miss) as 'catch_miss',
  avg(human_pass) as 'human_pass',
  avg(human_pass_miss) as 'human_pass_miss',
  avg(robot_pass) as 'robot_pass',
  avg(robot_pass_miss) as 'robot_pass_miss',
  avg(human_load) as 'human_load',
  avg(human_load_miss) as 'human_load_miss', 
  avg(floor_load) as 'floor_load',
  avg(floor_load_miss) as 'floor_load_miss',
  avg(other_possess) as 'other_possess',
  avg(dropped_balls) as 'dropped_balls'
FROM match_data
GROUP BY team_number